#PBS -S /bin/bash
#PBS -l walltime=00:29:00
#PBS -l nodes=1:ppn=1
#PBS -N qvatest-cpu
#PBS -o qvatest-cpu.out
#PBS -m abe
#PBS -M diegoarmino@gmail.com
#PBS -l pmem=4GB

cd $PBS_O_WORKDIR
module load intel/2013 gsl

export QVA_HOME=${HOME}/dev/qumvia
export PATH="${PATH}:${QVA_HOME}/bin"
export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:${MKLROOT}/lib/intel64"

echo Host = `hostname`
echo Date = `date`

MDEXE=$QVA_HOME/bin/qumvia.cpu

${MDEXE} -i input.iqv -o output.oqv -c coordinates.cqv -q romanowski.qqv 

